# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [41]:
import pandas as pd
import numpy as np
import re

In [72]:
insurance_data=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
insurance_data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [73]:
insurance_data.info

<bound method DataFrame.info of      Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
3     WW63253  California      M              Bachelor
4     GA49547  Washington      M  High School or Below
...       ...         ...    ...                   ...
4003      NaN         NaN    NaN                   NaN
4004      NaN         NaN    NaN                   NaN
4005      NaN         NaN    NaN                   NaN
4006      NaN         NaN    NaN                   NaN
4007      NaN         NaN    NaN                   NaN

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
3                 764586.18%      0.0                 106.0
4                 536307.65%  36357.0                  68.0
...                      ...      ...                   ...
4003                     NaN      NaN                   NaN
4004                     NaN      NaN                   NaN
4005                     NaN      NaN                   NaN
4006                     NaN      NaN                   NaN
4007                     NaN      NaN                   NaN

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car
1                       1/0/00   Personal Auto  Four-Door Car
2                       1/0/00   Personal Auto   Two-Door Car
3                       1/0/00  Corporate Auto            SUV
4                       1/0/00   Personal Auto  Four-Door Car
...                        ...             ...            ...
4003                       NaN             NaN            NaN
4004                       NaN             NaN            NaN
4005                       NaN             NaN            NaN
4006                       NaN             NaN            NaN
4007                       NaN             NaN            NaN

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
3             529.881344
4              17.269323
...                  ...
4003                 NaN
4004                 NaN
4005                 NaN
4006                 NaN
4007                 NaN

[4008 rows x 11 columns]>

In [43]:
insurance_data.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [44]:
insurance_data=insurance_data.rename(columns={
        "Customer": "customer",
        "ST": "state",
        "GENDER": "gender",
        "Education": "education",
        "Customer Lifetime Value": "customer_lifetime_value",
        "Income": "income",
        "Monthly Premium Auto": "monthly_premium_auto",
        "Number of Open Complaints": "number_of_open_complaints",
        "Policy Type": "policy_type",
        "Vehicle Class": "vehicle_class", 
        "Total Claim Amount": "total_claim_amount",
    })

In [45]:
insurance_data.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [55]:
insurance_data['gender'] = (
    insurance_data['gender']
    .str.lower()
    .replace({
        'f': 'F',
        'female': 'F',
        'femal': 'F',
        'm': 'M',
        'male': 'M'
    })
)

insurance_data['gender'].unique()

array([nan, 'F', 'M'], dtype=object)

In [54]:
insurance_data['state'] = insurance_data['state'].replace({
    'AZ': 'Arizona',
    'Cali': 'California',
    'WA': 'Washington'
})

insurance_data['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [53]:
insurance_data['education'] = insurance_data['education'].replace({
    'Bachelors': 'Bachelor'
})

insurance_data['education'].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [60]:
insurance_data['customer_lifetime_value'] = (
    insurance_data['customer_lifetime_value']
    .str.replace('%', '', regex=False)
)

insurance_data['customer_lifetime_value'].unique()

array([nan, '697953.59', '1288743.17', ..., '2031499.76', '323912.47',
       '899704.02'], shape=(1028,), dtype=object)

In [56]:
insurance_data['vehicle_class'] = insurance_data['vehicle_class'].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

insurance_data['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [61]:
#Customer lifetime value should be numeric
insurance_data['customer_lifetime_value'] = (
    insurance_data['customer_lifetime_value']
    .str.replace('%', '', regex=False)
    .astype(float)
)

insurance_data['customer_lifetime_value'].sample

<bound method NDFrame.sample of 0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: float64>

In [65]:
#Number of open complaints has an incorrect format. Look at the different values it takes with unique() and take the middle value
insurance_data['number_of_open_complaints'] = (
    insurance_data['number_of_open_complaints']
    .str.split('/')
    .str[1]
    .astype(float)
)

insurance_data['number_of_open_complaints'].sample

AttributeError: Can only use .str accessor with string values!

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [69]:
insurance_data[insurance_data.isnull().any(axis=1)]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
11,VQ65197,California,NaN,College,819719.71,0.0,110.0,0.0,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70,77026.0,110.0,2.0,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89,99845.0,110.0,1.0,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17,83689.0,70.0,2.0,Corporate Auto,Four-Door Car,307.139132
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
insurance_data.columns[insurance_data.isnull().any()]

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [78]:
"gender" in insurance_data.columns

False

In [79]:
insurance_data = insurance_data.drop(columns=["gender"])

KeyError: "['gender'] not found in axis"

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [81]:
insurance_data[insurance_data.duplicated()]

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
insurance_data = insurance_data.drop_duplicates()
insurance_data[insurance_data.duplicated()]

Empty DataFrame
Columns: [Customer, ST, GENDER, Education, Customer Lifetime Value, Income, Monthly Premium Auto, Number of Open Complaints, Policy Type, Vehicle Class, Total Claim Amount]
Index: []

In [85]:
insurance_data.info

<bound method DataFrame.info of      Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
3     WW63253  California      M              Bachelor
4     GA49547  Washington      M  High School or Below
...       ...         ...    ...                   ...
1067  VJ51327        Cali      F  High School or Below
1068  GS98873     Arizona      F              Bachelor
1069  CW49887  California      F                Master
1070  MY31220  California      F               College
1071      NaN         NaN    NaN                   NaN

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
3                 764586.18%      0.0                 106.0
4                 536307.65%  36357.0                  68.0
...                      ...      ...                   ...
1067             2031499.76%  63209.0                 102.0
1068              323912.47%  16061.0                  88.0
1069              462680.11%  79487.0                 114.0
1070              899704.02%  54230.0                 112.0
1071                     NaN      NaN                   NaN

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car
1                       1/0/00   Personal Auto  Four-Door Car
2                       1/0/00   Personal Auto   Two-Door Car
3                       1/0/00  Corporate Auto            SUV
4                       1/0/00   Personal Auto  Four-Door Car
...                        ...             ...            ...
1067                    1/2/00   Personal Auto            SUV
1068                    1/0/00   Personal Auto  Four-Door Car
1069                    1/0/00    Special Auto            SUV
1070                    1/0/00   Personal Auto   Two-Door Car
1071                       NaN             NaN            NaN

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
3             529.881344
4              17.269323
...                  ...
1067          207.320041
1068          633.600000
1069          547.200000
1070          537.600000
1071                 NaN

[1072 rows x 11 columns]>

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here